# Generated by Django 3.1.7 on 2021-03-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand']},
        ),
    ]
